# -*- coding: utf-8 -*-
"""rpg_hero

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOm9Dv5xN5_dwVG7ktI8TOoUrtNtVwJX
"""

#create class
class Hero:

  #create class attributes
  def __init__(self, name:str, hp:int):
    self.name = name
    self.hp = hp

  #create methods
  def take_damage(self, amount:int):
    self.hp -= amount
    print(f"{self.name} took {amount} damage!")
    print(f"Remaining HP: {self.hp}.")

#create two seperate instances (objects)
arthur = Hero("Arthur", 100)
morgana = Hero("Morgana", 100)

print("Initial State: ")
print(f"{arthur.name} Remaining HP: {arthur.hp}")
print(f"{morgana.name} Remaining HP: {morgana.hp}\n")

#ex. hero gets damaged
arthur.take_damage(30)  #therefore...

print("\n FInal State: ")
print(f"Arthur's final HP: {arthur.hp}")
print(f"Morgana's final HP: {morgana.hp}")
